/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import modelo.Quedada;

/**
 *
 * @author VSPC-ETERNALSTORM2V5
 */
public class InicioPanel extends javax.swing.JPanel {

    private int numQuedadas;
    private Quedada quedada;

    /**
     * Creates new form InicioPanel
     *
     * @param quedada
     * @param numQuedadas
     */
    public InicioPanel(Quedada quedada, int numQuedadas) {
        initComponents();
        this.quedada = quedada;
        this.numQuedadas = numQuedadas;
        creaPanelesSiHay();
        //QUE ME PASEN EL NUMERO DE QUEDADAS

    }

    public InicioPanel() {
        initComponents();
        this.numQuedadas = 0;
    }

    public int getNumQuedadas() {
        return numQuedadas;
    }

    public void setNumQuedadas(int numQuedadas) {
        this.numQuedadas = numQuedadas;
    }

    public JPanel getPnlQuedadas() {
        return pnlQuedadas;
    }

    public void setPnlQuedadas(JPanel pnlQuedadas) {
        this.pnlQuedadas = pnlQuedadas;
    }

    public JScrollPane getScrollInicio() {
        return scrollInicio;
    }

    public void setScrollInicio(JScrollPane scrollInicio) {
        this.scrollInicio = scrollInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollInicio = new javax.swing.JScrollPane();
        pnlQuedadas = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Inicio");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlQuedadasLayout = new javax.swing.GroupLayout(pnlQuedadas);
        pnlQuedadas.setLayout(pnlQuedadasLayout);
        pnlQuedadasLayout.setHorizontalGroup(
            pnlQuedadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        pnlQuedadasLayout.setVerticalGroup(
            pnlQuedadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        scrollInicio.setViewportView(pnlQuedadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlQuedadas;
    private javax.swing.JScrollPane scrollInicio;
    // End of variables declaration//GEN-END:variables

    public void creaPanelesSiHay() {
        GridLayout gL = new GridLayout(numQuedadas, 1, 1, 1);
        pnlQuedadas.setLayout(gL);
        int i = 0;
        if (numQuedadas != 0) {
            do {
                pnlQuedadas.add(new MiPanelQuedada(quedada));
                i++;
            } while (i < numQuedadas);
        }

    }
}
