/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author VSPC-ETERNALSTORM2V5
 */
public class MiPanelSeguidos extends javax.swing.JPanel {

    /**
     * Creates new form MiPanel
     */
    private final String nombreSeguido;
    private final String apellido1Seguido;
    private final String apellido2Seguido;
    private final String nickSeguido;
    
    public MiPanelSeguidos() {
        initComponents();
        this.nombreSeguido = "";
        this.apellido1Seguido = "";
        this.apellido2Seguido = "";
        this.nickSeguido = "";
    }
    
    public MiPanelSeguidos(String nombreSeguido, String apellido1Seguido, String apellido2Seguido, String nickSeguido) {
        initComponents();
        this.nombreSeguido = nombreSeguido;
        this.apellido1Seguido = apellido1Seguido;
        this.apellido2Seguido = apellido2Seguido;
        this.nickSeguido = nickSeguido;
        ponerTextoEtiqueta(nombreSeguido, apellido1Seguido, apellido2Seguido, nickSeguido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreYApellidos = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblNombreYApellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombreYApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreYApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNickname.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNickname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        evt.getLocationOnScreen();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNombreYApellidos;
    // End of variables declaration//GEN-END:variables

    private void ponerTextoEtiqueta(String nombreSeguido, String apellido1Seguido, String apellido2Seguido, String nickSeguido) {
        lblNickname.setText(nickSeguido);
        lblNombreYApellidos.setText(nombreSeguido + " " + apellido1Seguido + "" + apellido2Seguido);
    }
    
}
