/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author VSPC-ETERNALSTORM2V5
 */
public class SeguidosPanel extends javax.swing.JPanel {
    
    private int numSeguidos;
    private final String nombreSeguido;
    private final String apellido1Seguido;
    private final String apellido2Seguido;
    private final String nickSeguido;

    /**
     * Creates new form InicioPanel
     *
     */
    public SeguidosPanel(int numSeguidos, String nombreSeguido, String apellido1Seguido, String apellido2Seguido, String nickSeguido) {
        initComponents();
        this.numSeguidos = numSeguidos;
        this.nombreSeguido = nombreSeguido;
        this.apellido1Seguido = apellido1Seguido;
        this.apellido2Seguido = apellido2Seguido;
        this.nickSeguido = nickSeguido;
    }
    
    public SeguidosPanel() {
        initComponents();
        this.numSeguidos = 0;
        this.nombreSeguido = "";
        this.nickSeguido = "";
        this.apellido1Seguido = "";
        this.apellido2Seguido = "";
    }
    
    public int getNumSeguidos() {
        return numSeguidos;
    }
    
    public void setNumSeguidos(int numSeguidos) {
        this.numSeguidos = numSeguidos;
    }
    
    public JLabel getjLabel1() {
        return jLabel1;
    }
    
    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    
    public JPanel getPnlQuedadas() {
        return pnlQuedadas;
    }
    
    public void setPnlQuedadas(JPanel pnlQuedadas) {
        this.pnlQuedadas = pnlQuedadas;
    }
    
    public JScrollPane getScrollInicio() {
        return scrollInicio;
    }
    
    public void setScrollInicio(JScrollPane scrollInicio) {
        this.scrollInicio = scrollInicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollInicio = new javax.swing.JScrollPane();
        pnlQuedadas = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("MeetUpers");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlQuedadasLayout = new javax.swing.GroupLayout(pnlQuedadas);
        pnlQuedadas.setLayout(pnlQuedadasLayout);
        pnlQuedadasLayout.setHorizontalGroup(
            pnlQuedadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        pnlQuedadasLayout.setVerticalGroup(
            pnlQuedadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        scrollInicio.setViewportView(pnlQuedadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlQuedadas;
    private javax.swing.JScrollPane scrollInicio;
    // End of variables declaration//GEN-END:variables

    public void creaPanelesSiHay() {
        /*GridLayout lay = new GridLayout(16, 0, 1, 1);
        jPanel1.setLayout(lay);
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());
        jPanel1.add(new MiPanel());*/
        //Cuando llegue al Usuario lo mas probable un String tipo "Quedada"
        //Creará un panel quedada (el que tiene toda la informacion ) y otro el que tiene la informacion reducida
        //Tambien por la linea de comandos llegará cuantas quedadas hay
        GridLayout gL = new GridLayout(numSeguidos, 1, 1, 1);
        pnlQuedadas.setLayout(gL);
        int i = 0;
        do {
            pnlQuedadas.add(new MiPanelSeguidos(nombreSeguido, apellido1Seguido, apellido2Seguido, nickSeguido));
            i++;
        } while (i < numSeguidos);
        
    }
}
